### ISSUE TITLE
liblinear is crashing

### ISSUE THREAD

**Issue by jetmonk** [melisgl/cl-libsvm#1]
I'm getting an unhandled memory fault in liblinear on OSX SBCL, inside liblinear::%train after running (cl-liblinear::test).     Did liblinear ever work?  I'm using the MacPorts liblinear.   

Also, it seems that all of the `(foreign-slot-value p 'problem-struct 'y) ` etc should be changed to `(foreign-slot-value p '(:struct problem-struct) 'y)`  to reflect updates in cffi.

**Comment by melisgl** [comment]
Fixed the crash in 3cb3e2f9aac1936608bf60e34bc882a8bd6363de.
